apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://charts.concrnt.net/
    name: concrnt
    version: 0.0.3
    releaseName: concrnt
    namespace: concrnt
    valuesFile: ./values.yaml

generators:
  - ./configmap-generator.yaml

